server.port=${PORT:10000}

spring.datasource.url=jdbc:h2:mem:clinica-demo;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

app.seed-demo-data=true
app.seed-admin-login=${ADMIN_LOGIN:admin}
app.seed-admin-password=${ADMIN_PASSWORD:Luquinha12@}
app.seed-admin-name=${ADMIN_NAME:Dona da Clinica}
